version: 2
executorType: docker
containerInfo:
  - image: golang:1.7
stages:
  build:
    workDir: /go/src/github.com/danackerson/ackerson.de-go
    steps:
      - type: checkout
      # Build & Test
      - type: shell
        name: "Install JUnit & Setup Test Path"
        command: |
          go get github.com/jstemmer/go-junit-report
          mkdir -p /tmp/test-results
      - type: shell
        command: |
          set -eu
          go get -t -d -v ./...
          go test -v -race ./... | go-junit-report > /tmp/test-results/unit-tests.xml
          env GOOS=linux GOARCH=386 go build server.go
          docker build -t danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM .
          docker run -d -p 443:8443 -p 80:8080 -e prodSession=true --name ackerson.de danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM
          curl -k --retry 10 --retry-delay 5 -v https://localhost/ | grep Ackerson
          docker logs ackerson.de
      # NOPE: https://discuss.circleci.com/t/getting-started-docker-engine/8957
      - type: test-results-store
        path: /tmp/test-results
      # Upload container to dockerHub, Deploy container to droplet & Launch
      - type: deploy
        command: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          docker push danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM
          ssh ackersond@deploy.ackerson.de docker pull danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM
          ssh ackersond@deploy.ackerson.de docker rm -f ackerson.de; true
          ssh ackersond@deploy.ackerson.de docker run -d --restart=always -p 443:8443 -p 80:8080 -e CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM -e prodSession=true -e ackSecret=$ackSecret -e ackWunder=$ackWunder -v /home/core/certs:/root/certs:ro -v /app/public --name ackerson.de danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM
