kind: Service
apiVersion: v1
metadata:
  name: homepage
spec:
  ports:
    - name: homepage
      port: 8080
      protocol: TCP
  selector:
    app: homepage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: homepage
    spec:
      restartPolicy: Always
      nodeSelector:
        traefik: proxy
      containers:
        - name: homepage
          image: danackerson/ackerson.de:vg{{GITHUB_RUN_ID}}
          ports:
            - name: homepage
              containerPort: 8080
          envFrom:
            - secretRef:
                name: homepage-env-secrets

---

apiVersion: v1
kind: Secret
metadata:
  name: homepage-env-secrets
data:
  GITHUB_RUN_ID: {{GITHUB_RUN_ID_B64}}
  COOKIE_SECRET: {{COOKIE_SECRET_B64}}
  DARKSKY_API_KEY: {{DARKSKY_API_KEY_B64}}
  CTX_JOIN_API_KEY: {{CTX_JOIN_API_KEY_B64}}
  CTX_DROPBOX_ACCESS_TOKEN: {{CTX_DROPBOX_ACCESS_TOKEN_B64}}

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
spec:
  redirectRegex:
    regex: ^https://www.{{HOMEPAGE_HOSTNAME}}/(.*)
    replacement: https://{{HOMEPAGE_HOSTNAME}}/${1}
    permanent: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: default
spec:
  entryPoints:
    - web
    - secure
  routes:
  - match: Host(`{{HOMEPAGE_HOSTNAME}}`,`www.{{HOMEPAGE_HOSTNAME}}`)
    middlewares:
    - name: tls-redirect
    - name: www-redirect
    - name: careful-ratelimit
    kind: Rule
    services:
    - name: homepage
      port: 8080
