version: 2
jobs:
  build:
    docker:
      - image: golang:alpine
    working_directory: /go/src/github.com/danackerson/ackerson.de-go
    steps:
      - checkout
      - run:
          name: "Fetch dependencies, build and test"
          command: |
            apk add -U curl build-base git

            go get github.com/gobuffalo/packr/packr
            go get github.com/jstemmer/go-junit-report
            mkdir -p /tmp/test-results

            go get -t -d -v ./...
            go test -v ./... | go-junit-report > /tmp/test-results/unit-tests.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

      - setup_remote_docker
      - run:
          name: "Install Docker CE"
          command: |
            curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$CTX_DOCKER_ENGINE_VERSION.tgz && tar --strip-components=1 -xvzf docker-$CTX_DOCKER_ENGINE_VERSION.tgz -C /usr/local/bin
            rm docker-$CTX_DOCKER_ENGINE_VERSION.tgz && rm -f /var/cache/apk/*

      - run:
          name: "Build & push docker image"
          command: |
            env GOOS=linux GOARCH=386 packr build server.go
            docker build --compress -t danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM .
            docker login -u $CTX_DOCKER_USER -p $CTX_DOCKER_PASS
            docker tag danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM danackerson/ackerson.de:latest
            docker push danackerson/ackerson.de:vc$CIRCLE_BUILD_NUM
            docker push danackerson/ackerson.de:latest
            echo vc$CIRCLE_BUILD_NUM > last_docker_push

      - persist_to_workspace:
          root: /go/src/github.com/danackerson/ackerson.de-go
          paths:
            - last_docker_push

  deploy:
    docker:
      - image: alpine
    steps:
      - add-ssh-keys:
          fingerprints:
            - $CTX_SSH_DEPLOY_FINGERPRINT

      - run:
          name: Disable Digital Ocean firewall for deploy
          command: |
            apk add -U jq ca-certificates curl openssh-client
            curl -s https://raw.githubusercontent.com/danackerson/digitalocean/master/utils/addSSHipFW.sh | sh

      - attach_workspace:
          at: /tmp

      - run:
          name: "Upload to DockerHub, deploy container to Digital Ocean Droplet & launch"
          command: |
            export DEPLOY_SERVER=deploy.ackerson.de
            if [ $DEPLOY_SERVER_IP ]; then
              export DEPLOY_SERVER=$DEPLOY_SERVER_IP
            fi
            echo "Deploying to $DEPLOY_SERVER..."

            export DEPLOY_CONNECT="ssh -o StrictHostKeyChecking=no ackersond@$DEPLOY_SERVER"

            if [ -f /tmp/last_docker_push ]; then
              export LAST_DOCKER_PUSH=`cat /tmp/last_docker_push`
            else
              export LAST_DOCKER_PUSH=latest
            fi
            $DEPLOY_CONNECT docker pull danackerson/ackerson.de:$LAST_DOCKER_PUSH

            export DOCKER_RUN="docker run -d --restart=always --network='web' \
              -e CIRCLE_BUILD_NUM=$LAST_DOCKER_PUSH \
              -e CTX_JOIN_API_KEY=$CTX_JOIN_API_KEY \
              -e ackSecret=$ackSecret -e ackWunder=$ackWunder \
              -e CTX_DIGITALOCEAN_SPACES_KEY=$CTX_DIGITALOCEAN_SPACES_KEY \
              -e CTX_DIGITALOCEAN_SPACES_SECRET=$CTX_DIGITALOCEAN_SPACES_SECRET \
              -e CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC=$CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC \
              --label='traefik.backend=homepage' \
              --label='traefik.docker.network=web' \
              --label='traefik.frontend.passHostHeader=true'
              --label='traefik.frontend.rule=Host:ackerson.de,www.ackerson.de' \
              --label='traefik.enable=true' \
              --label='traefik.port=8080' \
              -v data-volume:/app/public/downloads \
              --name homepage danackerson/ackerson.de:$LAST_DOCKER_PUSH"

            if [ $DEPLOY_SERVER_IP ]; then
              $DEPLOY_CONNECT $DOCKER_RUN
            else
              $DEPLOY_CONNECT docker rm -f homepage || true
              $DEPLOY_CONNECT $DOCKER_RUN
            fi

      - run:
          name: Reenable Digital Ocean firewall
          command: |
            curl -s https://raw.githubusercontent.com/danackerson/digitalocean/master/utils/dropSSHipFW.sh | sh
          when: always

workflows:
  version: 2
  build-deploy:
    jobs:
        - build:
            context: org-global
        - deploy:
            context: org-global
            requires:
              - build
