name: Deploy ackerson.de homepage

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ca_pub_fingerprint:
        description: fingerprint of CA signed user cert
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN: ${{ secrets.CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN }}
      CTX_DIGITALOCEAN_FIREWALL: ${{ secrets.CTX_DIGITALOCEAN_FIREWALL }}
      CTX_SSH_DEPLOY_FINGERPRINT: ${{ secrets.CTX_SSH_DEPLOY_FINGERPRINT }}
      SSH_CXN: ${{ secrets.CTX_IPV6_MASTER_HOME }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Test application
        run: |
          go mod tidy
          go get -u github.com/jstemmer/go-junit-report

          mkdir -p /tmp/test-results
          export `go env | grep GOPATH | tr -d \"`
          go test -v ./... | $GOPATH/bin/go-junit-report > /tmp/test-results/unit-tests.xml
      - name: Upload & archive test results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: /tmp/test-results/unit-tests.xml

      - name: Build application and docker image
        run: |
          go get -u github.com/gobuffalo/packr/v2/packr2
          go mod tidy

          export `go env | grep GOPATH | tr -d \"`
          $GOPATH/bin/packr2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o homepage

          docker build --compress -t danackerson/ackerson.de:vg$GITHUB_RUN_ID .
          docker login -u ${{ secrets.CTX_DOCKER_USER }} -p ${{ secrets.CTX_DOCKER_PASS }}
          docker tag danackerson/ackerson.de:vg$GITHUB_RUN_ID danackerson/ackerson.de:latest
          docker push --all-tags danackerson/ackerson.de

      - name: Deploy to DO
        run: |
          git clone https://github.com/ackersonde/digitaloceans.git
          cd digitaloceans
          go get -t -d -v ./...
          go build do.go
          cd ../

          public_ip_address=$(curl -s https://checkip.amazonaws.com)
          ./digitaloceans/do -fn=firewallSSH -allow=true -ip=$public_ip_address -tag=traefik

          mkdir ~/.ssh
          cat <<EOF >~/.ssh/id_rsa
          ${{ secrets.CTX_DIGITALOCEAN_SSH_PRIVKEY }}
          EOF
          chmod 400 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no root@ackerson.de "\
            docker rm -f homepage || true && \
            docker run -d --restart=always \
              -e DARKSKY_API_KEY=${{ secrets.CTX_DARKSKY_API_KEY }} \
              -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
              -e ORG_HOW_YOU_LIKE_ME_NOW_B64=${{ secrets.ORG_HOW_YOU_LIKE_ME_NOW_B64 }} \
              -e ORG_THIS_ONES_FOR_ME_B64=${{ secrets.ORG_THIS_ONES_FOR_ME_B64 }} \
              --label='traefik.enable=true' \
              --label='traefik.http.routers.homepage.middlewares=secHeaders@file' \
              --label='traefik.http.routers.homepage.tls.certResolver=letsencrypt' \
              --label='traefik.http.routers.homepage.tls.domains=ackerson.de' \
              --label='traefik.http.routers.homepage.rule=Host(\`ackerson.de\`) || Host(\`www.ackerson.de\`)' \
              --name homepage danackerson/ackerson.de:vg$GITHUB_RUN_ID"

          rm -Rf ~/.ssh ~/.docker/config.json
          ./digitaloceans/do -fn=firewallSSH -allow=false -ip=$public_ip_address

          curl -s -o /dev/null -X POST -d token=${{ secrets.CTX_SLACK_NOTIFICATIONS_TOKEN }} -d channel=C092UE0H4 \
            -d text="<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID | $GITHUB_REPOSITORY @ $GITHUB_RUN_ID>" \
            https://slack.com/api/chat.postMessage
